/* Generated by Nebius TS generator. DO NOT EDIT! */

import { Registry } from '../../../src/runtime/protos/registry.js';

// Local registry instance. Generated index files register messages & enums via side-effects.
export const protoRegistry = new Registry();

// (Entries added via side-effect imports in per-directory index.ts files.)
