import fs from 'fs';
import path from 'path';

/*
 * Copies generated google.protobuf descriptor types into the generator so it
 * can bootstrap before src/api is available.
 *
 * Source: src/api/google/protobuf/index.ts
 * Dest:   scripts/generator/google/protobuf/index.ts
 *
 * The copy rewrites runtime imports for its new location.
 */

const projectRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(projectRoot, '.');
const SRC_FILE = path.join(repoRoot, 'src', 'api', 'google', 'protobuf', 'index.ts');
const DEST_FILE = path.join(projectRoot, 'scripts', 'generator', 'google', 'protobuf', 'index.ts');

function rewriteImports(code: string): string {
  // The generated file imports from ../../../runtime/protos relative to src/api/google/protobuf
  // After copying into scripts/generator/google/protobuf we need a path from there to src/runtime/protos.
  // Location math:
  //   original file location: src/api/google/protobuf/index.ts
  //   new file location:      scripts/generator/google/protobuf/index.ts
  // We want to keep runtime imports pointing at the runtime sources under src/runtime.
  // From new location to src/runtime/protos: ../../../../src/runtime/protos
  return code.replace(
    /from\s+"\.\.\/\.\.\/\.\.\/runtime\/protos/g,
    'from "../../../../src/runtime/protos.js',
  );
}

function main() {
  if (!fs.existsSync(SRC_FILE)) {
    console.warn(
      `[sync-descriptors] Skip: source file not found (expected after clean). ${SRC_FILE}`,
    );
    return;
  }
  let code = fs.readFileSync(SRC_FILE, 'utf8');
  code = rewriteImports(code);
  const header = '/* Vendored copy. AUTO-GENERATED by sync-descriptors.ts. DO NOT EDIT. */\n';
  fs.mkdirSync(path.dirname(DEST_FILE), { recursive: true });
  fs.writeFileSync(DEST_FILE, header + '\n' + code, 'utf8');
  console.log(
    '[sync-descriptors] Updated',
    path.relative(path.resolve(projectRoot, '..'), DEST_FILE),
  );
}

if (require.main === module) {
  main();
}
