import * as fs from 'fs';
import * as path from 'path';

function main() {
  const root = path.resolve(__dirname, '../..');
  const pkgPath = path.join(root, 'package.json');
  const outDir = path.join(root, 'src');
  const outFile = path.join(outDir, 'version.ts');

  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  const version = pkg.version;

  fs.mkdirSync(outDir, { recursive: true });

  const content =
    `// Auto-generated by scripts/version-gen.ts. Do not edit.\n` +
    `export const VERSION = '${version}';\n`;

  fs.writeFileSync(outFile, content);
  console.log(`Wrote ${path.relative(root, outFile)} with VERSION=${version}`);
}

main();
