name: Update API and regenerate project

on:
  workflow_dispatch: # Manual trigger
  repository_dispatch: # when triggered remotely
    types:
      - updated-api
  # push:
  #   paths:
  #   - 'nebius-api'
  #   - 'nebius-api/**'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v5
        with:
          ssh-key: ${{ secrets.AUTOCOMMITTER_PRIVATE_KEY }}
          submodules: recursive

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
        env:
          # Ensure devDependencies are installed for codegen, lint and tests
          NPM_CONFIG_PRODUCTION: false

      - name: Bump version
        run: |
          npm version patch --no-git-tag-version
          git add package.json package-lock.json

      - name: Update API submodule
        run: |
          git submodule update --remote nebius-api
          git add nebius-api

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Run auth test
        env:
          NEBIUS_LOG: TRACE
          NEBIUS_LOG_OUTPUT: stderr
          FORCE_COLOR: 1
          GRPC_VERBOSITY: DEBUG
          GRPC_TRACE: 'index,channel,connectivity_state,dns_resolver,pick_first,round_robin,subchannel,transport,keepalive'
        run: npm run test:noserver -- --runInBand --testPathPatterns='auth_integration.test.ts' -t "federation flow"

      - name: Run basic tests
        env:
          NEBIUS_LOG: DEBUG
          NEBIUS_LOG_OUTPUT: stderr
          FORCE_COLOR: 1
        run: npm run test:noserver -- --runInBand

      - name: Run build tests
        env:
          NEBIUS_LOG: DEBUG
          NEBIUS_LOG_OUTPUT: stderr
          FORCE_COLOR: 1
        run: npm run test:builds -- --runInBand

      - name: Run E2E tests
        env:
          NEBIUS_E2E_CONFIG_B64: ${{ secrets.NEBIUS_E2E_CONFIG_B64 }}
          NEBIUS_LOG: DEBUG
          NEBIUS_LOG_OUTPUT: stderr
          FORCE_COLOR: 1
          GRPC_VERBOSITY: DEBUG
          GRPC_TRACE: 'index,channel,connectivity_state,dns_resolver,pick_first,round_robin,subchannel,transport,keepalive'
        run: npm run test:e2e

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Auto-update API to: $(git -C nebius-api log -1 --format='%h, %ci')"

      - name: Push and pull changes
        run: |
          git push origin main
          git pull
          git status
          git branch -r --contains HEAD

      - name: Tag commit
        run: |
          git status --porcelain || exit 1
          TAG="v$(node -p "require('./package.json').version")"
          git tag $TAG

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          tags: true
          ssh: true
          force_with_lease: true

  notify-slack-on-failure:
    name: Notify Slack on failure
    if: failure()
    needs: [update]
    runs-on: ubuntu-latest
    steps:
      - name: Post text to a Slack channel
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_OAUTH_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL }}
            text: |
              🚨 Workflow *${{ github.workflow }}* failed on <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>
              <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>
