name: Update API and regenerate project

on:
  workflow_dispatch: # Manual trigger
  repository_dispatch: # when triggered remotely
    types:
      - updated-api
  # push:
  #   paths:
  #   - 'nebius-api'
  #   - 'nebius-api/**'

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.check_changes.outputs.changes_detected }}

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v5
        with:
          ssh-key: ${{ secrets.AUTOCOMMITTER_PRIVATE_KEY }}
          submodules: recursive

      - name: Check for Changes
        id: check_changes
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up Node.js
        if: steps.check_changes.outputs.changes_detected == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          npm ci
        env:
          # Ensure devDependencies are installed for codegen, lint and tests
          NPM_CONFIG_PRODUCTION: false

      - name: Bump version
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          npm version patch --no-git-tag-version
          git add package.json package-lock.json

      - name: Build
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: npm run build

      - name: Lint
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: npm run lint

      - name: Run auth test
        if: steps.check_changes.outputs.changes_detected == 'true'
        env:
          NEBIUS_LOG: TRACE
          NEBIUS_LOG_OUTPUT: stderr
          FORCE_COLOR: 1
          GRPC_VERBOSITY: DEBUG
          GRPC_TRACE: 'index,channel,connectivity_state,dns_resolver,pick_first,round_robin,subchannel,transport,keepalive'
        run: npm run test:noserver -- --runInBand --testPathPatterns='auth_integration.test.ts' -t "federation flow"

      - name: Run basic tests
        if: steps.check_changes.outputs.changes_detected == 'true'
        env:
          NEBIUS_LOG: DEBUG
          NEBIUS_LOG_OUTPUT: stderr
          FORCE_COLOR: 1
        run: npm run test:noserver -- --runInBand

      - name: Run build tests
        if: steps.check_changes.outputs.changes_detected == 'true'
        env:
          NEBIUS_LOG: DEBUG
          NEBIUS_LOG_OUTPUT: stderr
          FORCE_COLOR: 1
        run: npm run test:builds -- --runInBand

      - name: Run E2E tests
        if: steps.check_changes.outputs.changes_detected == 'true'
        env:
          NEBIUS_E2E_CONFIG_B64: ${{ secrets.NEBIUS_E2E_CONFIG_B64 }}
          NEBIUS_LOG: DEBUG
          NEBIUS_LOG_OUTPUT: stderr
          FORCE_COLOR: 1
          GRPC_VERBOSITY: DEBUG
          GRPC_TRACE: 'index,channel,connectivity_state,dns_resolver,pick_first,round_robin,subchannel,transport,keepalive'
        run: npm run test:e2e

      - name: Commit changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Auto-update API to: $(git -C nebius-api log -1 --format='%h, %ci')"

      - name: Push and pull changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git push origin main
          git pull
          git status
          git branch -r --contains HEAD

    # - name: Tag commit
    #   if: steps.check_changes.outputs.changes_detected == 'true'
    #   run: |
    #     make tag-ver

    # - name: Push changes
    #   if: steps.check_changes.outputs.changes_detected == 'true'
    #   uses: ad-m/github-push-action@master
    #   with:
    #     tags: true
    #     ssh: true
    #     force_with_lease: true

#   notify-slack-on-failure:
#     name: Notify Slack on failure
#     if: failure()
#     needs: [update]
#     runs-on: ubuntu-latest
#     steps:
#       - name: Post text to a Slack channel
#         uses: slackapi/slack-github-action@v2.1.1
#         with:
#           method: chat.postMessage
#           token: ${{ secrets.SLACK_OAUTH_TOKEN }}
#           payload: |
#             channel: ${{ secrets.SLACK_CHANNEL }}
#             text: |
#               🚨 Workflow *${{ github.workflow }}* failed on <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>
#               <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>
