name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - api-auto-update

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci
        env:
          # Ensure devDependencies are installed for codegen, lint and tests
          NPM_CONFIG_PRODUCTION: false

      - name: Generate sources
        run: npm run generate

      - name: Lint
        run: npm run lint

      - name: Run auth test
        env:
          NEBIUS_LOG: TRACE
          NEBIUS_LOG_OUTPUT: stderr
          FORCE_COLOR: 1
          GRPC_VERBOSITY: DEBUG
          GRPC_TRACE: 'index,channel,connectivity_state,dns_resolver,pick_first,round_robin,subchannel,transport,keepalive'
        run: npm run test:noserver -- --runInBand --testPathPatterns='auth_integration.test.ts' -t "federation flow"

      - name: Run basic tests
        env:
          NEBIUS_LOG: DEBUG
          NEBIUS_LOG_OUTPUT: stderr
          FORCE_COLOR: 1
        run: npm run test:noserver -- --runInBand

      - name: Run E2E tests
        env:
          NEBIUS_E2E_CONFIG_B64: ${{ secrets.NEBIUS_E2E_CONFIG_B64 }}
          NEBIUS_LOG: DEBUG
          NEBIUS_LOG_OUTPUT: stderr
          FORCE_COLOR: 1
          GRPC_VERBOSITY: DEBUG
          GRPC_TRACE: 'index,channel,connectivity_state,dns_resolver,pick_first,round_robin,subchannel,transport,keepalive'
        run: npm run test:e2e
