name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - api-auto-update

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci
        env:
          # Ensure devDependencies are installed for codegen, lint and tests
          NPM_CONFIG_PRODUCTION: false

      - name: Generate sources
        run: npm run generate

      - name: Lint
        run: npm run lint

      - name: Check HTTP connectivity to api.testing.nebius.cloud:443
        run: |
          status=$(curl --silent --show-error --head --write-out '%{http_code}' --output /dev/null --max-time 10 https://api.testing.nebius.cloud:443 || echo "000")
          case "$status" in
            2??|3??|403|404)
              echo "Host reachable, status $status"
              ;;
            *)
              echo "ERROR: Unexpected HTTP status $status" >&2
              exit 1
              ;;
          esac

      - name: Run tests
        env:
          NEBIUS_E2E_CONFIG_B64: ${{ secrets.NEBIUS_E2E_CONFIG_B64 }}
        run: npm test
